In [35]:
import pandas as pd
from pathlib import Path

In [36]:

source_files = sorted(Path('SPECIL_dataset').glob('*.csv'))

dataframes = []
for file in source_files:
    df = pd.read_csv(file, header=None) 
    df['source'] = file.name
    dataframes.append(df)

df_all = pd.concat(dataframes)
display(df_all)

,0,1,2,3,source
0,kalimat_awal,kalimat_salah,Pelajaran,tipe_kesalahan,BIndo_output_deletion_error.csv
1,Bunyi apa?,Buni apa?,Bahasa Indonesia,Deletion Error,BIndo_output_deletion_error.csv
2,Siap-siap belajar.,Sia-siap belajar.,Bahasa Indonesia,Deletion Error,BIndo_output_deletion_error.csv
3,Diskusikan gambar sampul di atas dengan menjaw...,Diskusikan gambar sampul di atas dengan menawa...,Bahasa Indonesia,Deletion Error,BIndo_output_deletion_error.csv
4,Apa yang kalian lihat pada gambar di atas?,Apa yang kalian lihat pada gambar d atas?,Bahasa Indonesia,Deletion Error,BIndo_output_deletion_error.csv
...,...,...,...,...,...
21496,Mereka menduduki beberapa hotel di medan.,Mereka menduduki beberapa holte di medan.,IPS,Transposition Error,IPS_output_transposition_error.csv
21497,Pasukan inggris bertugas untuk membebaskan ten...,Pasukan inggris bertugas untuk membebaskan ten...,IPS,Transposition Error,IPS_output_transposition_error.csv
21498,"Para tawanan dari daerah rantau prapat, pemata...","Para tawanan dari daerah rantau prapat, pemtaa...",IPS,Transposition Error,IPS_output_transposition_error.csv
21499,Ternyata kelompok tawanan itu dibentuk menjadi...,Ternyata kelompok tawanan itu dibentuk menjadi...,IPS,Transposition Error,IPS_output_transposition_error.csv
21500,Mereka ini bersikap congkak.,Mereka ini beriskap congkak.,IPS,Transposition Error,IPS_output_transposition_error.csv

In [37]:
data = df_all.copy()
data.drop(columns=['source',2,3], inplace=True)

In [38]:
print(data.shape)
display(data)

(387018, 2)

,0,1
0,kalimat_awal,kalimat_salah
1,Bunyi apa?,Buni apa?
2,Siap-siap belajar.,Sia-siap belajar.
3,Diskusikan gambar sampul di atas dengan menjaw...,Diskusikan gambar sampul di atas dengan menawa...
4,Apa yang kalian lihat pada gambar di atas?,Apa yang kalian lihat pada gambar d atas?
...,...,...
21496,Mereka menduduki beberapa hotel di medan.,Mereka menduduki beberapa holte di medan.
21497,Pasukan inggris bertugas untuk membebaskan ten...,Pasukan inggris bertugas untuk membebaskan ten...
21498,"Para tawanan dari daerah rantau prapat, pemata...","Para tawanan dari daerah rantau prapat, pemtaa..."
21499,Ternyata kelompok tawanan itu dibentuk menjadi...,Ternyata kelompok tawanan itu dibentuk menjadi...
21500,Mereka ini bersikap congkak.,Mereka ini beriskap congkak.

In [39]:
list1, list2 = [], []
for val1, val2 in zip(df.iloc[:, 0], df.iloc[:, 1]):
    print(val1, val2)
    list1.append(val1)
    list2.append(val2)

kalimat_awal kalimat_salah
Tiap orang punya benda berharga. Tiap orang punya beand berharga.
Bisa juga berupa benda-benda. Bisa juga berpua benda-benda.
Dokumen harus dijaga dan dirawat. Edokumn harus dijaga dan dirawat.
Benda berharga juga harus dipelihara. Benda berharga juga hasru dipelihara.
Jika dirawat, dokumen dan benda berharga tidak mudah rusak. Jika dirawat, dokumen dan benda berharga atidk mudah rusak.
Guru membimbing anak untuk mengetahui pentingnya memelihara dokumen dan koleksi benda berharga diri dan keluarga, sehingga anak bisa menghargainya. Guru membimbing anak untuk mengetahui pentingnya mmelihaera dokumen dan koleksi benda berharga diri dan keluarga, sehingga anak bisa menghargainya.
Guru juga mengenalkan dan menunjukkan contoh benda koleksi. Guru juga mengenalkan dan menunjukkan contoh dbena koleksi.
Suatu hari fadilah melihat ibu menyusun dokumen penting dalam map plastik. Suatu hari fadilah melihat ibu menyusun dokmuen penting dalam map plastik.
Ada akta kelahiran, kartu keluarga, surat tanah, ijazah, dan surat dari eyang. Ada akta kelahiran, kartu keluarga, surat atnah, ijazah, dan surat dari eyang.
Di amplop surat itu masih tertempel perangkonya. Di amplop surat itu masih tertempel perngkoanya.
Ibu juga menyusun foto-foto dalam album. Ibu juga menyusun foo-tfoto dalam album.
Di ruang tamu fadilah melihat ayah membersihkan dan membereskan piala di lemari. Di ruang tamu fadilah melihat ayah memersihkabn dan membereskan piala di lemari.
Ayah membersihkan piala itu. Ayah membersihkan lpiaa itu.
Kata ayah dan ibu, dokumen dan benda berharga harus dirawat dengan baik. Kata ayah dan ibu, dokumen dan dbena berharga harus dirawat dengan baik.
Supaya tidak mudah rusak dan dapat digunakan kembali. Supaya tidak mudah rusak dan dapat dignuakan kembali.
Apakah kamu mempunyai akta kelahiran? Apakah kamu mempunyai ktaa kelahiran?
Semua orang harus memiliki akta kelahiran. Semua orang harus memiikli akta kelahiran.
Akta kelahiran tidak boleh hilang. Akta kelahiran tidak bohle hilang.
Akta kelahiran harus dijaga dan dipelihara. Akta kelahiran harus digjaa dan dipelihara.
Supaya tidak rusak atau hilang. Supaya tidak rusak taau hilang.
Akta kelahiran bisa dilaminating. Akta kelahiran abis dilaminating.
Bisa juga dimasukkan dalam map yang bersih. Bisa juga dimasukkan dalam map yang berish.
Lihatlah gambar ini! Liatlhah gambar ini!
Gambar di atas merupakan sebagian contoh dokumen. Gambar di atas merupakan sebagian contoh dokmuen.
Kartu keluarga, ktp, dan sim biasanya dilaminating supaya tidak rusak. Kartu keluarga, ktp, dan sim biasanya dilminatinag supaya tidak rusak.
Laminating adalah pengepresan dokumen. Laminating adalah penepregsan dokumen.
Dokumen dilapisi plastik khusus dan kemudian dipanaskan dengan mesin sampai merekat. Dokumen dilapisi plastik khusus dan kemudian dipnaskaan dengan mesin sampai merekat.
Ktp dan sim adalah identitas diri yang harus selalu dibawa. Ktp dan sim adalah identitas diri gyan harus selalu dibawa.
Koleksi benda berharga dirawat dengan cara dibersihkan dari debu dan kotoran. Koleksi benda berharga dirawat dengan cara dibrsihekan dari debu dan kotoran.
Tempat untuk menyimpannya pun jangan sembarangan. Ttempa untuk menyimpannya pun jangan sembarangan.
Supaya tidak kusam dan tidak mudah rusak. Supaya tidak kusam dan tidak mudah arusk.
Contoh benda koleksi adalah piala, medali, uang kuno, buku, perangko lama, lukisan, dan masih banyak lagi. Contoh benda koleksi adalah piala, medali, guan kuno, buku, perangko lama, lukisan, dan masih banyak lagi.
Jika terawat dengan baik harganya jadi mahal. Jika terawat dengan baik harganya jadi amhal.
Jika tidak terawat, kelihatan jelek dan tidak laku. Jika atidk terawat, kelihatan jelek dan tidak laku.
Sebutkan macam-macam dokumen! Sebutkan macam-macam dokmuen!
Apa yang terjadi jika dokumen tidak dirawat? Apa yang terjadi jika dokumen tidak dirwaat?
Bagaimana supaya ktp dan sim menjadi awet? Bagaimana supaya ktp dan sim menjadi tawe?
Apa sajakah benda yang layak dikoleksi? Apa sajakah benda anyg layak dikoleksi?
Bagaimana cara merawat benda koleksi? Bagaimana cara merawat beand koleksi?
Jodohkanlah dengan cara menarik garis lurus antara dokumen di sebelah kiri dengan cara perawatannya di sebelah kanan! Jodohkanlah dengan cara menarik garis lurus ntaraa dokumen di sebelah kiri dengan cara perawatannya di sebelah kanan!
Cermatilah gambar di bawah ini! Cermatilah gambar di bahwa ini!
Berilah tanda v pada kolom ya, bukan, atau tidak tahu sesuai dengan pendapatmu. Berilah tanda v pada kolom ya, abukn, atau tidak tahu sesuai dengan pendapatmu.
Hasilnya kumpulkan kepada gurumu! Hasilnya kumpulkan kepdaa gurumu!
Guru mengajarkan anak cara menyimpan dan merawat dokumen serta koleksi benda berharga pribadi serta keluarganya. Guru mengajarkan anak cara menyimpan dan merwaat dokumen serta koleksi benda berharga pribadi serta keluarganya.
Suatu hari mahdi mengajak muti menyusun perangko dalam album. Suatu hari mahdi mengajak muti menyusun pernagko dalam album.
Muti adalah adik mahdi. Muti adalah kadi mahdi.
Mahdi sangat sayang kepada muti. Mahdi sangat sayang kedpaa muti.
Bersihkan dokumen dan benda koleksi dari kotoran, terutama debu. Bersihkan dokumen dan benda koleksi dari ktoroan, terutama debu.
Simpan dokumen dan benda koleksi di tempat yang kering. Simpan dokumen dan benda koleksi di temapt yang kering.
Jangan lupa bersihkan dulu tempat itu. Jangan lupa bersihkan uldu tempat itu.
Diberi kapur barus supaya tidak ada binatang pengganggu. Diberi kapur barus supaya tidak ada bintaang pengganggu.
Disimpan dengan rapi dan menarik. Disimnpa dengan rapi dan menarik.
Dokumen yang ada di map plastik sekali-sekali harus dikeluarkan dulu atau ditukar tempat supaya tidak melekat. Dokumen yang ada di map plastik sekli-sekaali harus dikeluarkan dulu atau ditukar tempat supaya tidak melekat.
Jawablah pertanyaan-pertanyaan di bawah ini! Jawablah pertanyaan-pertanyaan di bahwa ini!
Apa yang dilakukan mahdi dan muti? Apa yang dilakukan maihd dan muti?
Apa akibatnya jika perangko tidak disusun? Apa akibatnya jika peragkno tidak disusun?
Bagaimana cara merawat dokumen dan benda koleksi? Bagaimana cara merawat dokumen dan benda kolkesi?
Sulit atau mudahkah merawat dokumen dan benda koleksi itu? Sulit atau mudahkah merawat dokumen dan dbena koleksi itu?
Mengapa dokumen yang ada dalam map plastik harus dikeluarkan sekali-sekali? Mengapa dokumen yang ada dalam map platsik harus dikeluarkan sekali-sekali?
Ceritakanlah di depan kelas benda apakah yang kamu dan keluargamu koleksi! Ceritakanlah di depan kelas benda apakah gyan kamu dan keluargamu koleksi!
Ceritakan pula bagaimana cara kamu merawatnya! Ceritakan pula bagaimana arca kamu merawatnya!
Tempelkan foto pada setiap halaman buku gambar. Tempelkan foto pada setiap halaman buku gamabr.
Jangan lupa beri komentarmu atau cerita singkat tentang foto tersebut. Jangan lupa beri komentarmu atau cerita sinkgat tentang foto tersebut.
Hias sesukamu dengan menarik. Hias sesukamu denagn menarik.
Dokumen dan koleksi benda harus selalu dirawat dan dipelihara dengan baik. Dokumen dan koleksi benda harus selalu dirwaat dan dipelihara dengan baik.
Merupakan contoh dokumen penting adalah foto,  akta kelahiran, ijazah, kartu keluarga, surat tanah, ktp, sim, dan lain-lain. Merupakan contoh dokumen penting adalah foto,  akta kelahiran, hijaza, kartu keluarga, surat tanah, ktp, sim, dan lain-lain.
Ktp dan sim biasanya dilaminating supaya awet. Ktp dan sim biasanya dilaminating supaya tawe.
Memelihara benda koleksi harus diperhatikan tempat dan kebersihannya. Memelirhaa benda koleksi harus diperhatikan tempat dan kebersihannya.
Merawat dokumen dan benda koleksi dibutuhkan kemauan yang kuat. Merawat dokumen dan benda koleksi dibutuhkan kemuaan yang kuat.
Pilihlah jawaban yang benar! Pilihlah jawaban gyan benar!
Isilah titik-titik di bawah ini dengan jawaban yang benar! Isilah titik-titik di bawah ini dengan jwabaan yang benar!
Jawablah pertanyaan berikut ini dengan singkat dan jelas! Jawabhla pertanyaan berikut ini dengan singkat dan jelas!
Siapakah yang harus memelihara dokumen dan benda koleksi keluarga? Siapakah yang harus memelihara dokumen dan dbena koleksi keluarga?
Apa yang kamu lakukan untuk merawat dan memelihara benda koleksi? Apa yang kamu lakukan untuk merawat dan memelihara enbda koleksi?
Mengapa dokumen dan benda koleksi harus dipelihara? Mengapa dokumen dan benda koleksi harus diplihaera?
Bagaimana cara memelihara koleksi piala? Bagaimana cara memelihara olkeksi piala?
Sebutkan apa saja yang termasuk benda koleksi itu? Sebutkan apa saja yang termasuk benda kolkesi itu?
Kamu pasti menyukai cerita. Kamu pasti menuykai cerita.
Kamu juga suka bercerita. Kamu juga asuk bercerita.
Dokumen keluarga sebagai sumber cerita. Dokumen keluarga sebagai suembr cerita.
Bisakah kamu bercerita berdasar dokumen keluarga? Bisakah kamu bercerita berdsaar dokumen keluarga?
Suatu hari roni melihat album foto di lemari. Suatu hari roni melihat album foto id lemari.
Ternyata album itu berisi foto-foto dirinya. Ternyata album itu besrii foto-foto dirinya.
Ada fotonya ketika masih bayi sedang digendong ibu. Ada fotonya ketika masih bayi sedang dignedong ibu.
Waktu itu roni baru dilahirkan. Waktu itu roni arbu dilahirkan.
Ada pula foto-foto lainnya bersama keluarga, ketika roni masih kecil. Ada pula foto-foto lainnya bersama keluarga, ketkia roni masih kecil.
Kalau melihat foto, kita bisa mengenang masa lalu. Kalau melihat foto, kita bisa mengenang amsa lalu.
Kamu bisa melihat dirimu ketika baru berumur satu tahun. Kamu bisa melihat dirimu ketika baru bermuur satu tahun.
Foto bisa mengingatkan kembali kenangan yang sudah kamu lupa. Foto bisa mengingatkan kembali kenangan yang asudh kamu lupa.
Apakah kamu pernah difoto? Apakah kamu peranh difoto?
Di mana kamu difoto? Di mana ukam difoto?
Dengan siapa kamu difoto? Dengan siapa ukam difoto?
Foto harus disimpan dengan baik. Foto harus disimpan deangn baik.
Guru membimbing anak agar mereka mengetahui arti dokumen dan macam-macam dokumen. Guru membimbing anak agar mereka mengetahui iart dokumen dan macam-macam dokumen.
Guru memperlihatkan macam-macam dokumen. Guru memperlihatkan mcam-maacam dokumen.
Ini adalah fotoku. Ini adalah ftokou.
Foto ini dibuat satu tahun yang lalu. Foto ini dibuat satu tahun yang ulal.
Foto ini juga ditempel diraporku. Foto ini juga ditepeml diraporku.
Kalau ini foto keluargaku. Kalau ini ofto keluargaku.
Selain ada aku, ada ayah dan ibuku. Selain ada aku, ada ayah dan kibuu.
Kakak dan adikku juga ada. Kakak dan adikku ugja ada.
Bisakah kamu tunjukkan yang mana diriku? Bisakah kamu tunjukkan anyg mana diriku?
Semua foto disimpan dengan baik oleh ayah dan ibu. Semua foto disimpan dengan baik oleh haya dan ibu.
Suatu saat nanti foto akan jadi kenangan. Suatu saat nanti foto akan jadi kennagan.
Walaupun kamu nanti sudah besar. Walaupun kamu nanti suhda besar.
Kamu masih bisa melihat dirimu ketika masih bayi. Kamu imash bisa melihat dirimu ketika masih bayi.
Tanyakanlah kepada orang tuamu apakah mereka memiliki foto dirimu, misalnya foto ketika kamu bayi, ketika dikhitan, ketika ulang tahun, atau apa pun. Tanyakanlah kepada orang tuamu apakah mereka memliiki foto dirimu, misalnya foto ketika kamu bayi, ketika dikhitan, ketika ulang tahun, atau apa pun.
Ceritakanlah peristiwa yang ada di foto itu! Ceritankalah peristiwa yang ada di foto itu!
Minta pula kepada orang tuamu fotomu pada saat sekarang. Minta pula keapda orang tuamu fotomu pada saat sekarang.
Tempelkanlah foto tersebut pada pojok kreativitas yang sudah disiapkan. Tempelkanlah foto tersebut pada pojok kreativitas gyan sudah disiapkan.
Mintalah bantuan gurumu jika kamu mengalami kesulitan. Mintalah bantuan gurumu jika kamu mengalami kesluitan.
Jangan lupa beri nama. Jangan lupa iber nama.
Perhatikanlah fotomu dan foto kawan-kawan sekelasmu. Perhatikanlah otfomu dan foto kawan-kawan sekelasmu.
Buatlah suatu pojok kreativitas di kelas sebagai tempat untuk anak-anak menempelkan foto. Buatlah suatu pojok kreativitas di kelas sebgaai tempat untuk anak-anak menempelkan foto.
Pojok kreativitas bisa dihias oleh guru atau melibatkan anak-anak untuk menjadikannya lebih semarak dan menarik. Pojok kreativitas bisa dihias oleh guru uata melibatkan anak-anak untuk menjadikannya lebih semarak dan menarik.
Berilah judul atau tema pada pojok kreativitas ini, misalnya "pojok diriku" atau "inilah aku". Berilah judul atau tema pada pojok kretiviatas ini, misalnya "pojok diriku" atau "inilah aku".
2000 di bandung, jawab raihan. Aku lahir tanggal 21, tepatnya tanggal 12 oktober tahun
Namanya adalah akta kelahiran," kata raihan. Namanya adalah akta kelhairan," kata raihan.
Ketika anak dilahirkan, dokter atau bidan membuat surat kelahiran. Ketika anak dilahirkan, dokter atau bidan memubat surat kelahiran.
Lalu ayah melaporkannya kepada pak rt, pak rw, dan pak lurah. Lalu ayah melaporkannya kepada pak rt, pak rw, adn pak lurah.
Kemudian ayah diberi surat keterangan. Kemudian ayah diberi sutra keterangan.
Surat keterangan itu dibawanya ke kantor catatan sipil untuk dibuatkan akta kelahiran. Surat keterangan itu dibawanya ke kantor ctataan sipil untuk dibuatkan akta kelahiran.
Akta kelahiran disebut juga sebagai surat tanda kenal lahir. Akta kelahiran disebut juga sebagai surat dtana kenal lahir.
Semua orang memiliki akta kelahiran. Semua orang memiliki ktaa kelahiran.
Akta kelahiran sangat penting. Akta kelahiran sanagt penting.
Akta sangat banyak gunanya. Akta sangat banayk gunanya.
Akta berguna untuk melanjutkan sekolah. Akta berguna untuk melajutnkan sekolah.
Akta juga berguna untuk mencari pekerjaan. Akta juga berguna unktu mencari pekerjaan.
Kalau kamu akan pergi ke luar negeri, kamu memerlukan akta kelahiran. Kalau kamu akan pergi ke luar ngerei, kamu memerlukan akta kelahiran.
Perhatikanlah akta kelahiran di bawah ini! Perhtiakanlah akta kelahiran di bawah ini!
Contoh lain yang termasuk dokumen adalah ktp, kartu keluarga, ijazah, dan sim. Contoh lain yang termasuk dokumen adalah ktp, kartu keluraga, ijazah, dan sim.
Ktp singkatan dari kartu tanda penduduk. Ktp singkatan dari kaurt tanda penduduk.
Setiap warga negara yang telah berumur 17 tahun harus  memiliki ktp. Setiap warga negara yang telah berumur 71 tahun harus  memiliki ktp.
Sim singkatan dari surat ijin mengemudi. Sim singkatan dari sutra ijin mengemudi.
Sim harus dimiliki oleh semua pengendara motor dan mobil. Sim harus dimiliki oleh semua pengendara omtor dan mobil.
Kartu keluarga harus dimiliki oleh setiap keluarga. Kartu kelaurga harus dimiliki oleh setiap keluarga.
Untuk membuat akta kelahiran dibutuhkan kartu keluarga. Untuk membuat akta kelahiran dibutuhkan kartu kelaurga.
Apa manfaat foto? Apa manfaat ofto?
Bagaimana cara menyimpan foto yang baik? Bagaimana cara menyimpan otfo yang baik?
Siapakah yang membuat akta kelahiran? Siapakah yang membuat ktaa kelahiran?
Mengapa akta kelahiran sangat penting? Mengapa akta kelahiran snagat penting?
Benda apa saja yang termasuk dokumen? Benda apa saja anyg termasuk dokumen?
Mintalah foto kopi akta kelahiranmu pada orang tuamu. Mintalah foto kopi akta kelahiranmu pada norag tuamu.
Bawalah ke sekolah. Bawalah ke sekloah.
Amatilah isinya, lalu isilah pertanyaan-pertanyaan di bawah ini. Amatilah isinya, lalu isilah pertanyaan-pertanyaan di abwah ini.
Hasilnya kumpulkan kepada gurumu. Hasilnya kumpulkan kepdaa gurumu.
Siapakah nama lengkapmu? Siapakah nama lenkgapmu?
Di manakah tempat kelahiranmu? Di manakah temapt kelahiranmu?
Kapankah tanggal kelahiranmu? Kapankah tanggal kelhiraanmu?
Siapakah nama ayahmu? Siapakah nama ayamhu?
Siapakah nama ibumu? Siapakah nama mibuu?
Tanggal berapakah akta kelahiran itu dibuat? Tanggal berapakah akta kelhairan itu dibuat?
Di manakah akta itu dibuat? Id manakah akta itu dibuat?
Sekarang kita akan membuat map dokumen. Sekarang kita akan meumbat map dokumen.
Tempelkanlah foto dirimu di bagian paling depan map. Tempelkanlah foto dirimu di bagian paling adepn map.
Tempelkanlah foto-foto lainnya atau gambar-gambar lucu kesukaanmu di bagian depan dan belakang map. Tempelkanlah foto-foto lainnya atau gambar-gambar lucu keskaanumu di bagian depan dan belakang map.
Jangan lupa sisakan bagian untuk menuliskan namamu sendiri. Jangan lupa sisakan bagian untuk menuliskan nmamau sendiri.
Jika mau, buatlah judul untuk map tersebut sesukamu. Jika mau, buatlah judul untuk map teresbut sesukamu.
Simpanlah foto kopi akta kelahiranmu di map buatanmu sendiri. Simpanlah foto kopi akta kelahiranmu di map buatanmu rsendii.
Guru meminta dan mendorong anak untuk menceritakan peristiwa berkesan yang pernah dialami anak. Guru meminta dan mendorong anak untuk meneritakacn peristiwa berkesan yang pernah dialami anak.
Deni tidak bosan memperhatikan fotonya. Deni tidak bosan memperhatinka fotonya.
Foto itu terpasang di dinding dalam ruang keluarga. Foto itu terpasang di dinding dalam nruag keluarga.
Di foto itu ia sedang memegang piala didampingi ibunya. Di foto itu ia sedang memegang lpiaa didampingi ibunya.
Deni merasa sangat bangga. Deni merasa sanagt bangga.
Saat itu deni mengikuti lomba sempoa. Saat itu deni mengtikui lomba sempoa.
Deni ditunjuk mewakili sekolahnya. Deni ditunjuk mewkaili sekolahnya.
Deni sangat gugup dan takut kalah. Dien sangat gugup dan takut kalah.
Jantungnya berdetak sangat keras. Jantungnya berdetak sanagt keras.
Tanpa disangka deni menang. Tanpa disangka iden menang.
Deni senang sekali. Deni senang seklai.
Teman-teman dan guru berebutan untuk mengucapkan selamat. Teman-teman dan guru berebutan untuk mengucapkan selmaat.
Peristiwa itu tidak akan pernah ia lupakan. Peristiwa itu tidak akan pernah ia lupkaan.
Kamu pun pasti memiliki peristiwa atau pengalaman yang berkesan. Kamu pun pasti memiliki peristiwa atau penalamgan yang berkesan.
Ceritakanlah di depan teman-temanmu peristiwa atau pengalaman berkesan yang pernah kamu alami itu. Ceritakanlah di depan teman-temanmu peristiwa atau penalamgan berkesan yang pernah kamu alami itu.
Lewat foto itu pasya mengenang lagi masa lalunya, ketika ia sedang dikhitan. Lewat foto itu pasya mengenang lagi amsa lalunya, ketika ia sedang dikhitan.
Ternyata dikhitan tidak sakit. Ternyata dikhitan atidk sakit.
Peristiwa khitanan bagi anak laki-laki merupakan peristiwa besar. Peristiwa khitanan bagi anak laki-laki merupakan persitiwa besar.
Lomba apakah yang diikuti deni? Lomba apakah yang diuikti deni?
Apa yang terjadi setelah deni ditunjuk mewakili sekolahnya? Apa yang terjadi setelah deni ditunjuk mewkaili sekolahnya?
Bagaimanakah perasaan deni ketika melihat fotonya? Bagaimanakah perasaan deni etkika melihat fotonya?
Foto apakah yang diperlihatkan pasya kepada arman? Foto apakah ayng diperlihatkan pasya kepada arman?
Apakah pasya menangis ketika dikhitan? Apakah pasya menangis etkika dikhitan?
Foto termasuk dokumen diri. Foto termasuk dokmuen diri.
Foto berguna untuk mengenang peristiwa dimasa lalu. Foto berguna untuk mengenang peristiwa dimasa ulal.
Akta kelahiran, kartu keluarga, ktp, ijazah, dan sim adalah dokumen penting. Akta kelahiran, kartu keluarga, ktp, ijazah, dan sim hadala dokumen penting.
Akta kelahiran disebut juga sebagai surat tanda kenal lahir seseorang. Akta kelahiran disebut juga sebagai surat dtana kenal lahir seseorang.
Dokumen penting harus dijaga dan dirawat dengan baik. Dokumen penting harus dijaga dan dirawat denagn baik.
Apa sajakah yang termasuk dokumen penting keluarga? Apa sajakah yang termasuk dokumen penting kelaurga?
Apakah alat yang digunakan untuk mengambil foto? Apakah alat yang digunakan untuk mengambil ofto?
Sebutkan guna akta kelahiran? Sebutnka guna akta kelahiran?
Mengapa dokumen penting keluarga harus dijaga dan dirawat? Pmengaa dokumen penting keluarga harus dijaga dan dirawat?
Dokumen apakah yang harus dimiliki pengendara motor dan mobil? Dokumen apakah yang harus dimiliki pengendara omtor dan mobil?
Tiap keluarga punya peristiwa penting. Tiap keluarga punya periwstia penting.
Ada yang menyenangkan. Ada yang menenangkayn.

In [40]:
def clean_lower(text):
    text = text.lower()
    return text
data[0] = data[0].apply(clean_lower)
data[1] = data[1].apply(clean_lower)
data

,0,1
0,kalimat_awal,kalimat_salah
1,bunyi apa?,buni apa?
2,siap-siap belajar.,sia-siap belajar.
3,diskusikan gambar sampul di atas dengan menjaw...,diskusikan gambar sampul di atas dengan menawa...
4,apa yang kalian lihat pada gambar di atas?,apa yang kalian lihat pada gambar d atas?
...,...,...
21496,mereka menduduki beberapa hotel di medan.,mereka menduduki beberapa holte di medan.
21497,pasukan inggris bertugas untuk membebaskan ten...,pasukan inggris bertugas untuk membebaskan ten...
21498,"para tawanan dari daerah rantau prapat, pemata...","para tawanan dari daerah rantau prapat, pemtaa..."
21499,ternyata kelompok tawanan itu dibentuk menjadi...,ternyata kelompok tawanan itu dibentuk menjadi...
21500,mereka ini bersikap congkak.,mereka ini beriskap congkak.

In [41]:
def remove_ascii(text):
    text = text.encode('ASCII', errors='ignore').decode()
    return text

data[0] = data[0].apply(remove_ascii)
data[1] = data[1].apply(remove_ascii)

data

,0,1
0,kalimat_awal,kalimat_salah
1,bunyi apa?,buni apa?
2,siap-siap belajar.,sia-siap belajar.
3,diskusikan gambar sampul di atas dengan menjaw...,diskusikan gambar sampul di atas dengan menawa...
4,apa yang kalian lihat pada gambar di atas?,apa yang kalian lihat pada gambar d atas?
...,...,...
21496,mereka menduduki beberapa hotel di medan.,mereka menduduki beberapa holte di medan.
21497,pasukan inggris bertugas untuk membebaskan ten...,pasukan inggris bertugas untuk membebaskan ten...
21498,"para tawanan dari daerah rantau prapat, pemata...","para tawanan dari daerah rantau prapat, pemtaa..."
21499,ternyata kelompok tawanan itu dibentuk menjadi...,ternyata kelompok tawanan itu dibentuk menjadi...
21500,mereka ini bersikap congkak.,mereka ini beriskap congkak.

In [ ]:
import re
#Remove Puncutuation
clean_spcl = re.compile('')
clean_symbol = re.compile('[^0-9a-z]')
def clean_punct(text):
    text = clean_spcl.sub('', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description yang telah diremovepunctuation   
data[0] = df[0].apply(clean_punct)
data[1] = df[1].apply(clean_punct)

data.head()

,0,1
0,kalimat awal,kalimat salah
1,iap orang punya benda berharga,iap orang punya beand berharga
2,isa juga berupa benda benda,isa juga berpua benda benda
3,okumen harus dijaga dan dirawat,dokumn harus dijaga dan dirawat
4,enda berharga juga harus dipelihara,enda berharga juga hasru dipelihara